### ISSUE TITLE
Pacman needs root on systems which use the existing pacman

### ISSUE THREAD

**Issue by sharkwouter** [pspdev/psp-pacman#11]
I've discussed this with @carstene1ns yesterday. Since our patches don't apply to the system's pacman, root is required for software installation when using it. We have decided that we should build our version of pacman also on these systems, to lower the amount of work we need to do and to make sure it works for everyone. I will be working on this.

**Comment by sajattack** [comment]
I tried installing fjtrujy's toolchain without root and it got stuck trying to run python as root for psp-pacman.

**Comment by sajattack** [comment]
https://bpa.st/35KA
