### ISSUE TITLE
Set up a pacman repository

### ISSUE THREAD

**Issue by sharkwouter** [pspdev/psp-pacman#2]
I think this would be quite a challenge to set this up right, but I think it's needed.

I would propose we do the following:
- Build and upload the psptoolchain docker container to the dockerhub automatically with each commit to the master branch of the psptoolchain repo
- Convert psplibraries to just containing directories with PSPBUILDs
- Build all packages in the psplibraries repo automatically using the psptoolchain docker container
- Add to build packages to an arch repository we host, automatically, somehow

For this we need webhosting, a domain name and an SSL certificate, though, which is not free.

Let me know if you'd do any of this in a different way, there might be easier solutions.

I found some documentation on how setting up an Arch repository works. Since it took a while to find, here is the link:
https://wiki.archlinux.org/index.php/Pacman/Tips_and_tricks#Custom_local_repository

**Comment by carstene1ns** [comment]
Well, I had hosted an arch repository back some years ago, so I am familiar with the generic workflow.
Having it all automatically build is a good idea, however, only necessary rebuilds should happen (pacman can check for this and docker has a cache, so works).

We can distribute around different (own) servers and services like `bintray.com` (free open source plan).
There would be 1 master server and others will `rsync` from there. With package signing we do not need to worry our libraries get compromised somewhere.

Certificates are free with let's encrypt nowadays, so this is not a blocker. Webspace is not a problem, traffic needs to be measured.
That being said, I would sponsor a mirror (e.g. psdev.carsten.casa/psplibraries).

**Comment by sharkwouter** [comment]
Sounds good to me, although an additional change will be needed. With the dependencies which are currently being installed, Pacman is built without support for package signing. I'll look into this, it should be as simple as adding gpgme.

**Comment by carstene1ns** [comment]
Yeah, that should be done. Signing is not needed when a user builds a package locally, but for some internet repository this makes sense.

**Comment by sharkwouter** [comment]
Support for signed packages has been included in the docker container and the the toolchain dependency check now makes sure gpgme (which is needed to build with signing support) is installed.

**Comment by sharkwouter** [comment]
I wonder if it would be possible to set up a repo within the psplibraries repo by automatically building it with a github action and doing releases. Then we might have to put the db file in the repo, though, which is a binary file iirc.

**Comment by carstene1ns** [comment]
That is asking for trouble.

**Comment by sharkwouter** [comment]
Yeah, that's probably true :/
