### ISSUE TITLE
warning: no 'XferCommand' configured

### ISSUE THREAD

**Issue by markx86** [pspdev/psp-pacman#20]
When running the script `build-all.sh` from [pspdev/pspdev](https://github.com/pspdev/pspdev), I get an error when it tries to run `pacman -Sy`. These are the last three lines from the log (I'm going from memory here, if I have the time to rerun the whole script I'll update this):
```
...
warning: no 'XferCommand' configured
:: Synchronizing package databases...
error: no usable package repositories configured.
```
To solve this problem, I had to uncomment one of the `XferCommand` lines from the [`pacman.conf`](https://github.com/pspdev/psp-pacman/blob/master/config/pacman.conf) file (so either line 19 or line 20).
I'm creating an issue instead of a PR because this problem happens on my laptop but not on my desktop. Both systems run Fedora 37 (x86_64).

**Comment by tpimh** [comment]
Also happened to me when using the `pspdev/pspdev` Docker image. I had to install `gpgme` and `curl`, then uncomment curl XferCommand in order to make it work.

**Comment by sharkwouter** [comment]
Make sure you have libcurl-dev installed when you build. Otherwise you'll see this error.

> Also happened to me when using the pspdev/pspdev Docker image. I had to install gpgme and curl, then uncomment curl XferCommand in order to make it work.

Okay, that's a bug for sure. I'll see what I can do about this.

**Comment by sharkwouter** [comment]
This should be fixed now. Let me know if it's not.
