### ISSUE TITLE
Patch out pacman's own check for root privileges

### ISSUE THREAD

**Issue by carstene1ns** [pspdev/psp-pacman#4]

**Comment by sharkwouter** [comment]
Do you mean the one in makepkg?

**Comment by carstene1ns** [comment]
No, pacman itself checks whether it needs root privileges.
We just need to `return 0` here:
https://git.archlinux.org/pacman.git/tree/src/pacman/util.c#n104

**Comment by sharkwouter** [comment]
Makes sense. Using the ``-i`` option for makepkg also always asks for sudo permission.
