### ISSUE TITLE
Pacman uses bsdtar

### ISSUE THREAD

**Issue by sharkwouter** [pspdev/psp-pacman#6]
This is not really a problem, but we do need to make sure we install this with all the prepare scripts and inside the docker container. I put up this issue to not forget it.

**Comment by sharkwouter** [comment]
This PR is related: https://github.com/pspdev/psp-pacman/pull/5

**Comment by carstene1ns** [comment]
just for reference: pacman uses libarchive directly. makepkg uses the libarchive frontend bsdtar.

**Comment by sharkwouter** [comment]
This issue is no longer relevant. Libachive has been added to the dependencies in the readme a while ago.
